"""add_brand_to_product

Revision ID: 16b8eb569a4d
Revises: 001_initial_schema
Create Date: 2026-06-27 16:55:23.253889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b8eb569a4d'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'country',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'India'::character varying"))
    op.drop_constraint('uq_categories_slug', 'categories', type_='unique')
    op.drop_index('ix_categories_slug', table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.alter_column('coupons', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('uq_coupons_code', 'coupons', type_='unique')
    op.drop_index('ix_coupons_code', table_name='coupons')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.drop_constraint('uq_invoices_invoice_number', 'invoices', type_='unique')
    op.drop_constraint('uq_invoices_order_id', 'invoices', type_='unique')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.drop_index('ix_invoices_order_id', table_name='invoices')
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=True)
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.drop_constraint('uq_payments_order_id', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('product_images', 'r2_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('product_images', 'updated_at')
    op.drop_column('product_images', 'created_at')
    op.alter_column('product_variants', 'size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('product_variants', 'color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('uq_product_variants_sku', 'product_variants', type_='unique')
    op.drop_index('ix_product_variants_sku', table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.drop_constraint('uq_products_slug', 'products', type_='unique')
    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_constraint('uq_shipments_order_id', 'shipments', type_='unique')
    op.drop_index('ix_shipments_order_id', table_name='shipments')
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=True)
    op.drop_constraint('uq_shipping_providers_slug', 'shipping_providers', type_='unique')
    op.drop_index('ix_shipping_providers_slug', table_name='shipping_providers')
    op.create_index(op.f('ix_shipping_providers_slug'), 'shipping_providers', ['slug'], unique=True)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('uq_wishlist_items_user_id_product_id', 'wishlist_items', type_='unique')
    op.create_unique_constraint('uq_wishlist_user_product', 'wishlist_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wishlist_user_product', 'wishlist_items', type_='unique')
    op.create_unique_constraint('uq_wishlist_items_user_id_product_id', 'wishlist_items', ['user_id', 'product_id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_index(op.f('ix_shipping_providers_slug'), table_name='shipping_providers')
    op.create_index('ix_shipping_providers_slug', 'shipping_providers', ['slug'], unique=False)
    op.create_unique_constraint('uq_shipping_providers_slug', 'shipping_providers', ['slug'])
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.create_index('ix_shipments_order_id', 'shipments', ['order_id'], unique=False)
    op.create_unique_constraint('uq_shipments_order_id', 'shipments', ['order_id'])
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    op.create_unique_constraint('uq_products_slug', 'products', ['slug'])
    op.drop_column('products', 'brand')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index('ix_product_variants_sku', 'product_variants', ['sku'], unique=False)
    op.create_unique_constraint('uq_product_variants_sku', 'product_variants', ['sku'])
    op.alter_column('product_variants', 'color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('product_variants', 'size',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('product_images', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('product_images', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('product_images', 'r2_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_unique_constraint('uq_payments_order_id', 'payments', ['order_id'])
    op.add_column('order_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.create_index('ix_invoices_order_id', 'invoices', ['order_id'], unique=False)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_unique_constraint('uq_invoices_order_id', 'invoices', ['order_id'])
    op.create_unique_constraint('uq_invoices_invoice_number', 'invoices', ['invoice_number'])
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_index('ix_coupons_code', 'coupons', ['code'], unique=False)
    op.create_unique_constraint('uq_coupons_code', 'coupons', ['code'])
    op.alter_column('coupons', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=False)
    op.create_unique_constraint('uq_categories_slug', 'categories', ['slug'])
    op.alter_column('addresses', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False,
               existing_server_default=sa.text("'India'::character varying"))
    # ### end Alembic commands ###
